version: "3.7"

volumes:
  postgres:
  mongo:

services:
  postgres:
    image: bitnami/postgresql:14.1.0-debian-10-r31
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/bitnami/postgresql
    environment:
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres

  mongo:
    image: bitnami/mongodb:4.4.14-debian-10-r33
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/bitnami/mongodb
    environment:
      - MONGODB_ROOT_PASSWORD=root

  redis:
    image: bitnami/redis:7.0.9-debian-11-r5
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  polystore-inventory:
    image: ascoz/polystore-inventory:latest
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - PORT=8080
      - EUREKA_ENABLED=false
      - DATABASE_URL=jdbc:postgresql://postgres:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres

  polystore-order:
    image: ascoz/polystore-order:latest
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - PORT=8080
      - EUREKA_ENABLED=false
      - DATABASE_URL=jdbc:postgresql://postgres:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres

  polystore-catalog:
    image: ascoz/polystore-catalog:latest
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - PORT=8080
      - EUREKA_ENABLED=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=admin
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root

  polystore-gateway:
    image: ascoz/polystore-gateway:latest
    ports:
      - "8080:8080"
    environment:
      - EUREKA_ENABLED=false
