apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: ascoz/polystore-inventory:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: EUREKA_ENABLED
              value: "false"
            - name: DATABASE_URL
              value: "jdbc:postgresql://postgres:5432/postgres"
            - name: DATABASE_USERNAME
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "postgres"
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
